'use client';
import React, {useState, useEffect} from 'react';
import ReactPaginate from 'react-paginate';
import Header from '../../components/common/Header';
import Footer from '../../components/common/Footer';
import styled from 'styled-components';

// Datos mockeados de productos
const mockProducts
= [{id: 1, name: 'Tart Shells - Savory, 2', image: 'https://oaic.gov.au/mi/sit/amet/lobortis/sapien/sapien.xml?maecenas=eu&rhoncus=est&aliquam=congue&lacus=elementum&morbi=in&quis=hac&tortor=habitasse&id=platea&nulla=dictumst&ultrices=morbi&aliquet=vestibulum&maecenas=velit&leo=id&odio=pretium&condimentum=iaculis&id=diam&luctus=erat&nec=fermentum&molestie=justo&sed=nec&justo=condimentum&pellentesque=neque&viverra=sapien&pede=placerat&ac=ante&diam=nulla&cras=justo&pellentesque=aliquam&volutpat=quis&dui=turpis&maecenas=eget', description: 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.\n\nNulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', price: 858.38},
	{id: 2, name: 'Pepper - White, Ground', image: 'https://bbb.org/eu/tincidunt/in/leo/maecenas/pulvinar/lobortis.json?ut=eget&erat=elit&curabitur=sodales&gravida=scelerisque&nisi=mauris&at=sit&nibh=amet&in=eros&hac=suspendisse&habitasse=accumsan&platea=tortor&dictumst=quis&aliquam=turpis&augue=sed&quam=ante&sollicitudin=vivamus&vitae=tortor&consectetuer=duis&eget=mattis&rutrum=egestas&at=metus&lorem=aenean&integer=fermentum&tincidunt=donec', description: 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\n\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.\n\nDuis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', price: 437.24},
	{id: 3, name: 'Cheese - Brick With Pepper', image: 'http://chron.com/condimentum/curabitur/in/libero/ut/massa.js?suscipit=nunc&a=donec&feugiat=quis&et=orci&eros=eget&vestibulum=orci&ac=vehicula&est=condimentum&lacinia=curabitur&nisi=in&venenatis=libero&tristique=ut&fusce=massa&congue=volutpat&diam=convallis&id=morbi&ornare=odio&imperdiet=odio&sapien=elementum&urna=eu&pretium=interdum&nisl=eu&ut=tincidunt&volutpat=in', description: 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.\n\nMaecenas leo odio, condimentum id, luctus nec, molestie sed, justo. Pellentesque viverra pede ac diam. Cras pellentesque volutpat dui.', price: 202.78},
	{id: 4, name: 'Liqueur - Melon', image: 'https://hc360.com/neque/duis.json?dui=viverra&maecenas=eget&tristique=congue', description: 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.\n\nVestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', price: 943.46},
	{id: 5, name: 'Temperature Recording Station', image: 'http://princeton.edu/erat/vestibulum/sed/magna/at/nunc.js?quam=orci&suspendisse=luctus&potenti=et&nullam=ultrices&porttitor=posuere&lacus=cubilia&at=curae&turpis=nulla&donec=dapibus&posuere=dolor&metus=vel&vitae=est&ipsum=donec&aliquam=odio&non=justo&mauris=sollicitudin&morbi=ut&non=suscipit&lectus=a&aliquam=feugiat&sit=et&amet=eros&diam=vestibulum&in=ac&magna=est&bibendum=lacinia&imperdiet=nisi&nullam=venenatis&orci=tristique&pede=fusce&venenatis=congue&non=diam&sodales=id&sed=ornare&tincidunt=imperdiet&eu=sapien&felis=urna&fusce=pretium&posuere=nisl&felis=ut&sed=volutpat&lacus=sapien&morbi=arcu&sem=sed&mauris=augue&laoreet=aliquam&ut=erat&rhoncus=volutpat&aliquet=in&pulvinar=congue&sed=etiam&nisl=justo&nunc=etiam&rhoncus=pretium&dui=iaculis&vel=justo&sem=in&sed=hac&sagittis=habitasse&nam=platea&congue=dictumst&risus=etiam&semper=faucibus', description: 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.\n\nVestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', price: 863.63},
	{id: 6, name: 'Quail - Jumbo Boneless', image: 'http://squidoo.com/placerat/praesent/blandit/nam/nulla/integer.jpg?fermentum=tempus&donec=semper&ut=est&mauris=quam&eget=pharetra&massa=magna&tempor=ac&convallis=consequat&nulla=metus&neque=sapien&libero=ut&convallis=nunc&eget=vestibulum&eleifend=ante&luctus=ipsum&ultricies=primis&eu=in&nibh=faucibus&quisque=orci&id=luctus&justo=et&sit=ultrices&amet=posuere&sapien=cubilia&dignissim=curae&vestibulum=mauris&vestibulum=viverra&ante=diam&ipsum=vitae&primis=quam&in=suspendisse&faucibus=potenti&orci=nullam&luctus=porttitor&et=lacus&ultrices=at&posuere=turpis&cubilia=donec&curae=posuere&nulla=metus&dapibus=vitae&dolor=ipsum&vel=aliquam&est=non&donec=mauris&odio=morbi&justo=non&sollicitudin=lectus&ut=aliquam&suscipit=sit&a=amet&feugiat=diam', description: 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', price: 422.6},
	{id: 7, name: 'Muffin Mix - Lemon Cranberry', image: 'http://bandcamp.com/rutrum/rutrum.jpg?natoque=in&penatibus=libero&et=ut&magnis=massa&dis=volutpat&parturient=convallis&montes=morbi&nascetur=odio&ridiculus=odio&mus=elementum&etiam=eu&vel=interdum&augue=eu&vestibulum=tincidunt&rutrum=in&rutrum=leo&neque=maecenas&aenean=pulvinar&auctor=lobortis&gravida=est&sem=phasellus&praesent=sit&id=amet&massa=erat&id=nulla&nisl=tempus', description: 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', price: 909.96},
	{id: 8, name: 'Turkey - Breast, Boneless Sk On', image: 'https://wsj.com/aliquet/maecenas/leo.jsp?aliquam=mauris&lacus=sit&morbi=amet&quis=eros&tortor=suspendisse&id=accumsan&nulla=tortor&ultrices=quis&aliquet=turpis&maecenas=sed&leo=ante&odio=vivamus&condimentum=tortor&id=duis&luctus=mattis&nec=egestas&molestie=metus&sed=aenean&justo=fermentum&pellentesque=donec&viverra=ut&pede=mauris&ac=eget&diam=massa&cras=tempor&pellentesque=convallis&volutpat=nulla&dui=neque&maecenas=libero&tristique=convallis&est=eget&et=eleifend&tempus=luctus&semper=ultricies&est=eu&quam=nibh&pharetra=quisque&magna=id&ac=justo&consequat=sit&metus=amet&sapien=sapien&ut=dignissim&nunc=vestibulum&vestibulum=vestibulum&ante=ante&ipsum=ipsum&primis=primis&in=in&faucibus=faucibus', description: 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.\n\nPraesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', price: 54.62},
	{id: 9, name: 'Fruit Salad Deluxe', image: 'http://123-reg.co.uk/consequat/dui/nec/nisi/volutpat.png?vestibulum=convallis&ante=nulla&ipsum=neque&primis=libero&in=convallis&faucibus=eget&orci=eleifend&luctus=luctus&et=ultricies&ultrices=eu&posuere=nibh&cubilia=quisque&curae=id&donec=justo&pharetra=sit&magna=amet&vestibulum=sapien&aliquet=dignissim&ultrices=vestibulum&erat=vestibulum&tortor=ante&sollicitudin=ipsum&mi=primis', description: 'Sed ante. Vivamus tortor. Duis mattis egestas metus.\n\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', price: 919.93},
	{id: 10, name: 'Lobster - Base', image: 'http://boston.com/in/faucibus/orci.json?sociis=fermentum&natoque=donec&penatibus=ut&et=mauris&magnis=eget&dis=massa&parturient=tempor&montes=convallis&nascetur=nulla&ridiculus=neque', description: 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', price: 65.14},
	{id: 11, name: 'Lobster - Base', image: 'http://ca.gov/vel/augue/vestibulum.aspx?porttitor=ligula&pede=suspendisse&justo=ornare&eu=consequat&massa=lectus&donec=in&dapibus=est&duis=risus&at=auctor&velit=sed&eu=tristique&est=in&congue=tempus&elementum=sit&in=amet&hac=sem&habitasse=fusce&platea=consequat&dictumst=nulla&morbi=nisl&vestibulum=nunc&velit=nisl&id=duis&pretium=bibendum&iaculis=felis&diam=sed&erat=interdum&fermentum=venenatis&justo=turpis&nec=enim&condimentum=blandit&neque=mi&sapien=in&placerat=porttitor&ante=pede&nulla=justo&justo=eu&aliquam=massa&quis=donec&turpis=dapibus&eget=duis&elit=at&sodales=velit&scelerisque=eu&mauris=est&sit=congue&amet=elementum&eros=in&suspendisse=hac&accumsan=habitasse&tortor=platea&quis=dictumst&turpis=morbi&sed=vestibulum&ante=velit&vivamus=id&tortor=pretium&duis=iaculis&mattis=diam&egestas=erat&metus=fermentum&aenean=justo&fermentum=nec&donec=condimentum&ut=neque&mauris=sapien&eget=placerat&massa=ante&tempor=nulla&convallis=justo&nulla=aliquam&neque=quis&libero=turpis&convallis=eget&eget=elit&eleifend=sodales&luctus=scelerisque&ultricies=mauris&eu=sit', description: 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.\n\nIn hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\n\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', price: 883.68},
	{id: 12, name: 'Ecolab - Hand Soap Form Antibac', image: 'https://wsj.com/morbi/non.png?id=faucibus&ornare=orci&imperdiet=luctus&sapien=et&urna=ultrices&pretium=posuere&nisl=cubilia&ut=curae&volutpat=donec&sapien=pharetra&arcu=magna&sed=vestibulum&augue=aliquet&aliquam=ultrices&erat=erat&volutpat=tortor&in=sollicitudin&congue=mi&etiam=sit&justo=amet&etiam=lobortis&pretium=sapien&iaculis=sapien&justo=non&in=mi&hac=integer&habitasse=ac&platea=neque&dictumst=duis&etiam=bibendum&faucibus=morbi&cursus=non&urna=quam&ut=nec&tellus=dui&nulla=luctus&ut=rutrum&erat=nulla&id=tellus&mauris=in&vulputate=sagittis&elementum=dui&nullam=vel&varius=nisl&nulla=duis&facilisi=ac&cras=nibh&non=fusce&velit=lacus&nec=purus&nisi=aliquet&vulputate=at&nonummy=feugiat&maecenas=non&tincidunt=pretium&lacus=quis&at=lectus&velit=suspendisse&vivamus=potenti&vel=in&nulla=eleifend&eget=quam&eros=a&elementum=odio', description: 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.\n\nFusce consequat. Nulla nisl. Nunc nisl.', price: 847.81},
	{id: 13, name: 'Fish - Scallops, Cold Smoked', image: 'https://google.fr/cursus/id/turpis/integer/aliquet/massa/id.aspx?luctus=fermentum&et=donec&ultrices=ut&posuere=mauris&cubilia=eget&curae=massa&donec=tempor&pharetra=convallis&magna=nulla&vestibulum=neque&aliquet=libero&ultrices=convallis&erat=eget&tortor=eleifend&sollicitudin=luctus&mi=ultricies&sit=eu&amet=nibh&lobortis=quisque&sapien=id&sapien=justo&non=sit&mi=amet&integer=sapien&ac=dignissim&neque=vestibulum&duis=vestibulum', description: 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\n\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.\n\nMaecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', price: 425.95},
	{id: 14, name: 'Parasol Pick Stir Stick', image: 'https://gov.uk/imperdiet/sapien/urna.html?condimentum=at&curabitur=velit&in=vivamus&libero=vel&ut=nulla&massa=eget&volutpat=eros&convallis=elementum&morbi=pellentesque&odio=quisque&odio=porta&elementum=volutpat&eu=erat&interdum=quisque&eu=erat&tincidunt=eros&in=viverra&leo=eget&maecenas=congue&pulvinar=eget&lobortis=semper&est=rutrum&phasellus=nulla&sit=nunc&amet=purus&erat=phasellus&nulla=in&tempus=felis&vivamus=donec&in=semper&felis=sapien&eu=a&sapien=libero&cursus=nam&vestibulum=dui&proin=proin', description: 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.\n\nInteger tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\n\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', price: 73.89},
	{id: 15, name: 'Rootbeer', image: 'http://paypal.com/mauris.png?odio=tincidunt&elementum=nulla&eu=mollis&interdum=molestie&eu=lorem&tincidunt=quisque&in=ut&leo=erat&maecenas=curabitur&pulvinar=gravida&lobortis=nisi&est=at&phasellus=nibh&sit=in&amet=hac&erat=habitasse&nulla=platea&tempus=dictumst', description: 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\n\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.\n\nMaecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', price: 392.76},
	{id: 16, name: 'Wine - Rubyport', image: 'http://sohu.com/nam.xml?magnis=magnis&dis=dis&parturient=parturient&montes=montes&nascetur=nascetur&ridiculus=ridiculus&mus=mus&vivamus=vivamus&vestibulum=vestibulum&sagittis=sagittis&sapien=sapien&cum=cum&sociis=sociis&natoque=natoque&penatibus=penatibus&et=et&magnis=magnis&dis=dis&parturient=parturient&montes=montes&nascetur=nascetur&ridiculus=ridiculus&mus=mus&etiam=etiam&vel=vel&augue=augue&vestibulum=vestibulum&rutrum=rutrum&rutrum=rutrum&neque=neque&aenean=aenean&auctor=auctor&gravida=gravida&sem=sem&praesent=praesent&id=id&massa=massa&id=id&nisl=nisl&venenatis=venenatis&lacinia=lacinia&aenean=aenean&sit=sit&amet=amet&justo=justo&morbi=morbi', description: 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', price: 81.59},
	{id: 17, name: 'Red Snapper - Fresh, Whole', image: 'https://nhs.uk/hac/habitasse/platea/dictumst/etiam/faucibus/cursus.json?vel=cubilia&est=curae&donec=mauris&odio=viverra&justo=diam&sollicitudin=vitae&ut=quam&suscipit=suspendisse&a=potenti&feugiat=nullam&et=porttitor&eros=lacus&vestibulum=at&ac=turpis&est=donec&lacinia=posuere&nisi=metus&venenatis=vitae&tristique=ipsum&fusce=aliquam&congue=non&diam=mauris&id=morbi&ornare=non&imperdiet=lectus&sapien=aliquam&urna=sit&pretium=amet&nisl=diam&ut=in&volutpat=magna&sapien=bibendum&arcu=imperdiet&sed=nullam&augue=orci&aliquam=pede&erat=venenatis&volutpat=non&in=sodales&congue=sed&etiam=tincidunt&justo=eu&etiam=felis&pretium=fusce&iaculis=posuere&justo=felis&in=sed&hac=lacus&habitasse=morbi&platea=sem&dictumst=mauris&etiam=laoreet&faucibus=ut&cursus=rhoncus&urna=aliquet&ut=pulvinar&tellus=sed&nulla=nisl&ut=nunc', description: 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.\n\nIn hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', price: 548.61},
	{id: 18, name: 'Cheese - Brie, Triple Creme', image: 'https://netvibes.com/proin/at.xml?tellus=nibh&nulla=ligula&ut=nec&erat=sem&id=duis&mauris=aliquam&vulputate=convallis&elementum=nunc&nullam=proin&varius=at&nulla=turpis&facilisi=a&cras=pede&non=posuere&velit=nonummy&nec=integer&nisi=non&vulputate=velit&nonummy=donec&maecenas=diam&tincidunt=neque&lacus=vestibulum&at=eget&velit=vulputate&vivamus=ut&vel=ultrices&nulla=vel&eget=augue&eros=vestibulum&elementum=ante&pellentesque=ipsum&quisque=primis&porta=in&volutpat=faucibus&erat=orci&quisque=luctus&erat=et&eros=ultrices&viverra=posuere&eget=cubilia&congue=curae&eget=donec&semper=pharetra&rutrum=magna&nulla=vestibulum&nunc=aliquet&purus=ultrices&phasellus=erat&in=tortor&felis=sollicitudin&donec=mi&semper=sit&sapien=amet&a=lobortis&libero=sapien&nam=sapien&dui=non&proin=mi&leo=integer', description: 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.\n\nInteger tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', price: 488.78},
	{id: 19, name: 'Milk Powder', image: 'https://sfgate.com/vestibulum/rutrum.jpg?in=at&leo=nunc&maecenas=commodo&pulvinar=placerat&lobortis=praesent&est=blandit&phasellus=nam&sit=nulla&amet=integer&erat=pede&nulla=justo&tempus=lacinia&vivamus=eget&in=tincidunt&felis=eget&eu=tempus&sapien=vel&cursus=pede&vestibulum=morbi&proin=porttitor&eu=lorem&mi=id&nulla=ligula&ac=suspendisse&enim=ornare&in=consequat&tempor=lectus&turpis=in&nec=est&euismod=risus&scelerisque=auctor&quam=sed&turpis=tristique&adipiscing=in&lorem=tempus&vitae=sit&mattis=amet&nibh=sem&ligula=fusce&nec=consequat&sem=nulla&duis=nisl&aliquam=nunc&convallis=nisl&nunc=duis&proin=bibendum&at=felis&turpis=sed&a=interdum&pede=venenatis&posuere=turpis&nonummy=enim&integer=blandit&non=mi&velit=in', description: 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', price: 232.17},
	{id: 20, name: 'Cheese - Pied De Vents', image: 'http://bigcartel.com/ut.jpg?posuere=eu&nonummy=felis&integer=fusce&non=posuere&velit=felis&donec=sed&diam=lacus&neque=morbi&vestibulum=sem&eget=mauris&vulputate=laoreet&ut=ut&ultrices=rhoncus&vel=aliquet&augue=pulvinar', description: 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.\n\nCras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', price: 772.06},
	{id: 21, name: 'Campari', image: 'https://alibaba.com/justo/in/blandit/ultrices/enim/lorem/ipsum.json?potenti=in&nullam=faucibus&porttitor=orci&lacus=luctus&at=et&turpis=ultrices&donec=posuere&posuere=cubilia&metus=curae&vitae=duis&ipsum=faucibus&aliquam=accumsan&non=odio&mauris=curabitur&morbi=convallis&non=duis&lectus=consequat&aliquam=dui&sit=nec&amet=nisi&diam=volutpat&in=eleifend', description: 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.\n\nQuisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', price: 986.45},
	{id: 22, name: 'Chicken - Wings, Tip Off', image: 'https://uol.com.br/hac/habitasse/platea/dictumst/etiam/faucibus/cursus.xml?maecenas=condimentum&leo=id&odio=luctus&condimentum=nec&id=molestie&luctus=sed&nec=justo&molestie=pellentesque&sed=viverra&justo=pede&pellentesque=ac&viverra=diam&pede=cras&ac=pellentesque&diam=volutpat&cras=dui&pellentesque=maecenas&volutpat=tristique&dui=est&maecenas=et&tristique=tempus&est=semper&et=est&tempus=quam&semper=pharetra&est=magna&quam=ac&pharetra=consequat&magna=metus&ac=sapien&consequat=ut&metus=nunc&sapien=vestibulum&ut=ante&nunc=ipsum', description: 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.\n\nDonec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', price: 624.15},
	{id: 23, name: 'Mustard - Seed', image: 'https://cdc.gov/orci/luctus/et/ultrices.jsp?risus=erat&praesent=quisque&lectus=erat&vestibulum=eros&quam=viverra&sapien=eget&varius=congue&ut=eget&blandit=semper&non=rutrum&interdum=nulla&in=nunc&ante=purus&vestibulum=phasellus&ante=in&ipsum=felis&primis=donec&in=semper&faucibus=sapien&orci=a&luctus=libero&et=nam&ultrices=dui&posuere=proin&cubilia=leo&curae=odio&duis=porttitor&faucibus=id&accumsan=consequat&odio=in&curabitur=consequat&convallis=ut&duis=nulla&consequat=sed&dui=accumsan&nec=felis&nisi=ut&volutpat=at&eleifend=dolor&donec=quis&ut=odio&dolor=consequat&morbi=varius&vel=integer&lectus=ac&in=leo&quam=pellentesque&fringilla=ultrices&rhoncus=mattis&mauris=odio&enim=donec&leo=vitae&rhoncus=nisi&sed=nam&vestibulum=ultrices&sit=libero&amet=non&cursus=mattis&id=pulvinar&turpis=nulla&integer=pede&aliquet=ullamcorper&massa=augue&id=a&lobortis=suscipit&convallis=nulla&tortor=elit&risus=ac&dapibus=nulla&augue=sed', description: 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\n\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.\n\nMaecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', price: 132.8},
	{id: 24, name: 'Chocolate - Milk, Callets', image: 'http://narod.ru/hac/habitasse/platea/dictumst/morbi/vestibulum.html?faucibus=ante&accumsan=ipsum&odio=primis&curabitur=in&convallis=faucibus&duis=orci&consequat=luctus&dui=et&nec=ultrices&nisi=posuere&volutpat=cubilia&eleifend=curae&donec=mauris&ut=viverra&dolor=diam&morbi=vitae&vel=quam&lectus=suspendisse&in=potenti&quam=nullam&fringilla=porttitor&rhoncus=lacus&mauris=at&enim=turpis&leo=donec&rhoncus=posuere&sed=metus&vestibulum=vitae&sit=ipsum&amet=aliquam&cursus=non&id=mauris&turpis=morbi&integer=non&aliquet=lectus&massa=aliquam&id=sit&lobortis=amet&convallis=diam&tortor=in&risus=magna&dapibus=bibendum&augue=imperdiet&vel=nullam&accumsan=orci&tellus=pede&nisi=venenatis&eu=non&orci=sodales', description: 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.\n\nInteger tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', price: 384.27},
	{id: 25, name: 'Bar Energy Chocchip', image: 'https://huffingtonpost.com/orci/luctus/et/ultrices.html?quis=consectetuer&augue=adipiscing&luctus=elit&tincidunt=proin&nulla=risus&mollis=praesent', description: 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.\n\nAliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.\n\nSed ante. Vivamus tortor. Duis mattis egestas metus.', price: 371.89},
	{id: 26, name: 'Salmon - Atlantic, No Skin', image: 'https://rediff.com/massa/quis/augue/luctus.jpg?turpis=ante&nec=vel&euismod=ipsum&scelerisque=praesent&quam=blandit&turpis=lacinia&adipiscing=erat&lorem=vestibulum&vitae=sed&mattis=magna&nibh=at&ligula=nunc&nec=commodo&sem=placerat&duis=praesent&aliquam=blandit&convallis=nam&nunc=nulla&proin=integer&at=pede&turpis=justo&a=lacinia&pede=eget&posuere=tincidunt&nonummy=eget&integer=tempus&non=vel&velit=pede&donec=morbi&diam=porttitor&neque=lorem&vestibulum=id&eget=ligula&vulputate=suspendisse&ut=ornare&ultrices=consequat&vel=lectus&augue=in&vestibulum=est&ante=risus&ipsum=auctor&primis=sed&in=tristique&faucibus=in&orci=tempus&luctus=sit&et=amet&ultrices=sem&posuere=fusce&cubilia=consequat&curae=nulla&donec=nisl&pharetra=nunc&magna=nisl&vestibulum=duis&aliquet=bibendum&ultrices=felis&erat=sed&tortor=interdum&sollicitudin=venenatis&mi=turpis&sit=enim&amet=blandit&lobortis=mi&sapien=in&sapien=porttitor&non=pede&mi=justo&integer=eu&ac=massa&neque=donec', description: 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', price: 919.15},
	{id: 27, name: 'Pasta - Detalini, White, Fresh', image: 'http://bbb.org/justo/morbi/ut/odio/cras/mi.js?ultricies=cursus&eu=id&nibh=turpis&quisque=integer&id=aliquet&justo=massa&sit=id&amet=lobortis&sapien=convallis&dignissim=tortor&vestibulum=risus&vestibulum=dapibus&ante=augue&ipsum=vel&primis=accumsan&in=tellus&faucibus=nisi&orci=eu&luctus=orci&et=mauris&ultrices=lacinia&posuere=sapien&cubilia=quis&curae=libero&nulla=nullam&dapibus=sit&dolor=amet&vel=turpis&est=elementum&donec=ligula&odio=vehicula&justo=consequat&sollicitudin=morbi&ut=a&suscipit=ipsum&a=integer&feugiat=a&et=nibh&eros=in&vestibulum=quis&ac=justo&est=maecenas&lacinia=rhoncus&nisi=aliquam&venenatis=lacus&tristique=morbi&fusce=quis&congue=tortor&diam=id&id=nulla&ornare=ultrices&imperdiet=aliquet&sapien=maecenas&urna=leo&pretium=odio&nisl=condimentum&ut=id&volutpat=luctus&sapien=nec&arcu=molestie&sed=sed&augue=justo&aliquam=pellentesque&erat=viverra&volutpat=pede&in=ac&congue=diam&etiam=cras&justo=pellentesque&etiam=volutpat&pretium=dui&iaculis=maecenas&justo=tristique&in=est&hac=et&habitasse=tempus&platea=semper&dictumst=est&etiam=quam&faucibus=pharetra&cursus=magna&urna=ac&ut=consequat&tellus=metus&nulla=sapien&ut=ut&erat=nunc&id=vestibulum&mauris=ante&vulputate=ipsum&elementum=primis&nullam=in&varius=faucibus&nulla=orci', description: 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.\n\nPraesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.\n\nCras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', price: 722.43},
	{id: 28, name: 'Pepsi - 600ml', image: 'http://goodreads.com/penatibus/et/magnis.xml?porta=at&volutpat=feugiat&quam=non&pede=pretium&lobortis=quis&ligula=lectus&sit=suspendisse&amet=potenti&eleifend=in&pede=eleifend&libero=quam&quis=a&orci=odio&nullam=in&molestie=hac&nibh=habitasse&in=platea&lectus=dictumst&pellentesque=maecenas&at=ut&nulla=massa&suspendisse=quis&potenti=augue&cras=luctus&in=tincidunt&purus=nulla&eu=mollis&magna=molestie&vulputate=lorem&luctus=quisque&cum=ut&sociis=erat&natoque=curabitur&penatibus=gravida&et=nisi&magnis=at&dis=nibh&parturient=in&montes=hac&nascetur=habitasse&ridiculus=platea&mus=dictumst&vivamus=aliquam&vestibulum=augue&sagittis=quam&sapien=sollicitudin&cum=vitae&sociis=consectetuer&natoque=eget&penatibus=rutrum&et=at&magnis=lorem&dis=integer&parturient=tincidunt&montes=ante&nascetur=vel&ridiculus=ipsum&mus=praesent&etiam=blandit&vel=lacinia&augue=erat&vestibulum=vestibulum&rutrum=sed&rutrum=magna&neque=at&aenean=nunc', description: 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', price: 812.21},
	{id: 29, name: 'Pork - Back, Short Cut, Boneless', image: 'http://theatlantic.com/ultrices/enim.json?suspendisse=nunc&potenti=donec&nullam=quis&porttitor=orci&lacus=eget&at=orci&turpis=vehicula&donec=condimentum&posuere=curabitur&metus=in&vitae=libero&ipsum=ut&aliquam=massa&non=volutpat&mauris=convallis&morbi=morbi', description: 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\n\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.\n\nFusce consequat. Nulla nisl. Nunc nisl.', price: 879.54},
	{id: 30, name: 'Truffle - Peelings', image: 'http://jugem.jp/aliquam/convallis/nunc/proin.xml?sit=velit&amet=vivamus&erat=vel&nulla=nulla&tempus=eget&vivamus=eros&in=elementum&felis=pellentesque&eu=quisque&sapien=porta&cursus=volutpat&vestibulum=erat&proin=quisque&eu=erat&mi=eros&nulla=viverra&ac=eget&enim=congue&in=eget&tempor=semper&turpis=rutrum&nec=nulla&euismod=nunc&scelerisque=purus&quam=phasellus&turpis=in&adipiscing=felis&lorem=donec&vitae=semper&mattis=sapien&nibh=a&ligula=libero&nec=nam&sem=dui&duis=proin&aliquam=leo&convallis=odio&nunc=porttitor&proin=id&at=consequat&turpis=in&a=consequat&pede=ut&posuere=nulla&nonummy=sed&integer=accumsan&non=felis&velit=ut&donec=at&diam=dolor&neque=quis&vestibulum=odio&eget=consequat&vulputate=varius&ut=integer&ultrices=ac&vel=leo&augue=pellentesque&vestibulum=ultrices&ante=mattis&ipsum=odio&primis=donec&in=vitae&faucibus=nisi&orci=nam&luctus=ultrices&et=libero&ultrices=non&posuere=mattis&cubilia=pulvinar&curae=nulla&donec=pede&pharetra=ullamcorper&magna=augue', description: 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.\n\nNullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.\n\nIn quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', price: 193.06},
	{id: 31, name: 'Cape Capensis - Fillet', image: 'http://sourceforge.net/ante/ipsum/primis/in/faucibus/orci/luctus.jpg?tristique=eget&est=tincidunt&et=eget&tempus=tempus&semper=vel&est=pede&quam=morbi&pharetra=porttitor&magna=lorem&ac=id&consequat=ligula&metus=suspendisse&sapien=ornare&ut=consequat&nunc=lectus&vestibulum=in&ante=est&ipsum=risus&primis=auctor&in=sed&faucibus=tristique&orci=in&luctus=tempus&et=sit&ultrices=amet&posuere=sem&cubilia=fusce&curae=consequat&mauris=nulla&viverra=nisl&diam=nunc&vitae=nisl&quam=duis&suspendisse=bibendum&potenti=felis&nullam=sed&porttitor=interdum&lacus=venenatis&at=turpis&turpis=enim&donec=blandit&posuere=mi&metus=in&vitae=porttitor&ipsum=pede&aliquam=justo&non=eu&mauris=massa&morbi=donec&non=dapibus&lectus=duis&aliquam=at&sit=velit&amet=eu&diam=est&in=congue&magna=elementum&bibendum=in&imperdiet=hac', description: 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.\n\nNulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.\n\nCras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', price: 179.1},
	{id: 32, name: 'Cleaner - Bleach', image: 'https://ehow.com/lacus/morbi/quis.png?natoque=consectetuer&penatibus=eget&et=rutrum&magnis=at&dis=lorem&parturient=integer&montes=tincidunt&nascetur=ante&ridiculus=vel&mus=ipsum&vivamus=praesent&vestibulum=blandit&sagittis=lacinia&sapien=erat&cum=vestibulum&sociis=sed&natoque=magna&penatibus=at&et=nunc&magnis=commodo&dis=placerat', description: 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.\n\nAenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.\n\nCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', price: 110.94},
	{id: 33, name: 'Pastry - Lemon Danish - Mini', image: 'http://usgs.gov/integer.html?nunc=pellentesque&purus=at&phasellus=nulla&in=suspendisse&felis=potenti&donec=cras&semper=in&sapien=purus&a=eu&libero=magna&nam=vulputate&dui=luctus&proin=cum&leo=sociis&odio=natoque&porttitor=penatibus&id=et&consequat=magnis&in=dis&consequat=parturient&ut=montes&nulla=nascetur&sed=ridiculus&accumsan=mus&felis=vivamus&ut=vestibulum&at=sagittis&dolor=sapien&quis=cum&odio=sociis&consequat=natoque&varius=penatibus&integer=et&ac=magnis&leo=dis&pellentesque=parturient&ultrices=montes&mattis=nascetur&odio=ridiculus&donec=mus&vitae=etiam&nisi=vel&nam=augue&ultrices=vestibulum&libero=rutrum&non=rutrum&mattis=neque&pulvinar=aenean&nulla=auctor&pede=gravida&ullamcorper=sem&augue=praesent&a=id&suscipit=massa&nulla=id&elit=nisl&ac=venenatis&nulla=lacinia&sed=aenean&vel=sit&enim=amet&sit=justo&amet=morbi&nunc=ut&viverra=odio&dapibus=cras&nulla=mi&suscipit=pede&ligula=malesuada&in=in&lacus=imperdiet&curabitur=et&at=commodo&ipsum=vulputate&ac=justo&tellus=in&semper=blandit&interdum=ultrices&mauris=enim&ullamcorper=lorem', description: 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.\n\nNullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.', price: 860.28},
	{id: 34, name: 'Juice - Lemon', image: 'https://odnoklassniki.ru/orci/luctus.jsp?non=libero&sodales=quis&sed=orci&tincidunt=nullam&eu=molestie&felis=nibh&fusce=in&posuere=lectus&felis=pellentesque&sed=at&lacus=nulla&morbi=suspendisse&sem=potenti&mauris=cras&laoreet=in&ut=purus&rhoncus=eu&aliquet=magna&pulvinar=vulputate&sed=luctus&nisl=cum&nunc=sociis&rhoncus=natoque&dui=penatibus&vel=et&sem=magnis&sed=dis&sagittis=parturient&nam=montes&congue=nascetur&risus=ridiculus&semper=mus&porta=vivamus&volutpat=vestibulum&quam=sagittis&pede=sapien&lobortis=cum&ligula=sociis&sit=natoque&amet=penatibus&eleifend=et&pede=magnis&libero=dis&quis=parturient&orci=montes&nullam=nascetur&molestie=ridiculus&nibh=mus&in=etiam&lectus=vel&pellentesque=augue&at=vestibulum&nulla=rutrum&suspendisse=rutrum&potenti=neque&cras=aenean&in=auctor&purus=gravida&eu=sem&magna=praesent&vulputate=id&luctus=massa&cum=id&sociis=nisl&natoque=venenatis&penatibus=lacinia&et=aenean&magnis=sit&dis=amet&parturient=justo&montes=morbi&nascetur=ut&ridiculus=odio&mus=cras&vivamus=mi&vestibulum=pede&sagittis=malesuada&sapien=in&cum=imperdiet&sociis=et&natoque=commodo&penatibus=vulputate&et=justo&magnis=in', description: 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.\n\nInteger ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.\n\nNam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', price: 596.56},
	{id: 35, name: 'Cup - Paper 10oz 92959', image: 'http://tumblr.com/ornare/imperdiet/sapien/urna/pretium.png?sagittis=posuere&sapien=metus&cum=vitae&sociis=ipsum&natoque=aliquam&penatibus=non&et=mauris&magnis=morbi&dis=non&parturient=lectus&montes=aliquam&nascetur=sit&ridiculus=amet&mus=diam&etiam=in&vel=magna&augue=bibendum&vestibulum=imperdiet&rutrum=nullam&rutrum=orci&neque=pede&aenean=venenatis&auctor=non&gravida=sodales&sem=sed&praesent=tincidunt&id=eu&massa=felis&id=fusce&nisl=posuere', description: 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\n\nEtiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', price: 204.61},
	{id: 36, name: 'Syrup - Monin, Irish Cream', image: 'https://nih.gov/bibendum/imperdiet/nullam/orci/pede.js?eget=felis&tempus=eu&vel=sapien&pede=cursus&morbi=vestibulum&porttitor=proin&lorem=eu&id=mi&ligula=nulla&suspendisse=ac&ornare=enim&consequat=in&lectus=tempor&in=turpis&est=nec&risus=euismod&auctor=scelerisque&sed=quam&tristique=turpis&in=adipiscing&tempus=lorem&sit=vitae&amet=mattis', description: 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.\n\nProin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', price: 215.92},
	{id: 37, name: 'Beer - Steamwhistle', image: 'http://bloglines.com/libero/quis/orci/nullam.html?mauris=quis&lacinia=orci&sapien=nullam&quis=molestie&libero=nibh&nullam=in&sit=lectus&amet=pellentesque&turpis=at&elementum=nulla&ligula=suspendisse&vehicula=potenti&consequat=cras&morbi=in&a=purus&ipsum=eu&integer=magna&a=vulputate&nibh=luctus&in=cum&quis=sociis&justo=natoque&maecenas=penatibus&rhoncus=et&aliquam=magnis&lacus=dis&morbi=parturient&quis=montes&tortor=nascetur&id=ridiculus&nulla=mus&ultrices=vivamus&aliquet=vestibulum&maecenas=sagittis&leo=sapien&odio=cum&condimentum=sociis&id=natoque&luctus=penatibus&nec=et&molestie=magnis&sed=dis&justo=parturient&pellentesque=montes&viverra=nascetur&pede=ridiculus&ac=mus&diam=etiam&cras=vel&pellentesque=augue&volutpat=vestibulum&dui=rutrum&maecenas=rutrum&tristique=neque&est=aenean&et=auctor&tempus=gravida&semper=sem&est=praesent&quam=id&pharetra=massa&magna=id&ac=nisl&consequat=venenatis&metus=lacinia&sapien=aenean&ut=sit&nunc=amet&vestibulum=justo&ante=morbi&ipsum=ut&primis=odio&in=cras&faucibus=mi&orci=pede&luctus=malesuada&et=in&ultrices=imperdiet&posuere=et&cubilia=commodo&curae=vulputate&mauris=justo&viverra=in&diam=blandit&vitae=ultrices&quam=enim&suspendisse=lorem', description: 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.\n\nPhasellus in felis. Donec semper sapien a libero. Nam dui.\n\nProin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', price: 985.74},
	{id: 38, name: 'Coke - Diet, 355 Ml', image: 'https://washington.edu/nisi/volutpat/eleifend.xml?aliquet=sapien&maecenas=in&leo=sapien&odio=iaculis&condimentum=congue&id=vivamus&luctus=metus&nec=arcu&molestie=adipiscing&sed=molestie&justo=hendrerit&pellentesque=at&viverra=vulputate&pede=vitae&ac=nisl&diam=aenean&cras=lectus&pellentesque=pellentesque&volutpat=eget&dui=nunc&maecenas=donec&tristique=quis&est=orci&et=eget&tempus=orci&semper=vehicula&est=condimentum&quam=curabitur&pharetra=in&magna=libero&ac=ut&consequat=massa&metus=volutpat&sapien=convallis&ut=morbi&nunc=odio&vestibulum=odio&ante=elementum&ipsum=eu&primis=interdum&in=eu&faucibus=tincidunt&orci=in&luctus=leo&et=maecenas&ultrices=pulvinar&posuere=lobortis&cubilia=est&curae=phasellus&mauris=sit&viverra=amet&diam=erat&vitae=nulla&quam=tempus&suspendisse=vivamus&potenti=in&nullam=felis&porttitor=eu&lacus=sapien&at=cursus', description: 'Donec diam neque, vestibulum eget, vulputate ut, ultrices vel, augue. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec pharetra, magna vestibulum aliquet ultrices, erat tortor sollicitudin mi, sit amet lobortis sapien sapien non mi. Integer ac neque.', price: 374.21},
	{id: 39, name: 'Propel Sport Drink', image: 'https://pen.io/quisque/porta/volutpat/erat/quisque/erat/eros.aspx?praesent=ut&lectus=volutpat&vestibulum=sapien&quam=arcu&sapien=sed&varius=augue&ut=aliquam&blandit=erat&non=volutpat&interdum=in&in=congue&ante=etiam&vestibulum=justo&ante=etiam&ipsum=pretium&primis=iaculis&in=justo&faucibus=in&orci=hac&luctus=habitasse&et=platea&ultrices=dictumst&posuere=etiam&cubilia=faucibus&curae=cursus&duis=urna&faucibus=ut&accumsan=tellus&odio=nulla&curabitur=ut&convallis=erat&duis=id&consequat=mauris&dui=vulputate&nec=elementum', description: 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.\n\nPraesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.\n\nMorbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', price: 234.25},
	{id: 40, name: 'Monkfish Fresh - Skin Off', image: 'https://google.com/vitae/quam/suspendisse/potenti/nullam.html?at=sed&turpis=justo&donec=pellentesque&posuere=viverra&metus=pede&vitae=ac&ipsum=diam&aliquam=cras&non=pellentesque&mauris=volutpat&morbi=dui&non=maecenas&lectus=tristique&aliquam=est&sit=et&amet=tempus&diam=semper&in=est&magna=quam&bibendum=pharetra&imperdiet=magna&nullam=ac&orci=consequat&pede=metus&venenatis=sapien&non=ut&sodales=nunc&sed=vestibulum', description: 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.\n\nPellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', price: 604.28},
	{id: 41, name: 'Rabbit - Saddles', image: 'https://wunderground.com/imperdiet.jsp?odio=tellus&consequat=nisi&varius=eu&integer=orci', description: 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', price: 262.67},
	{id: 42, name: 'Sauerkraut', image: 'http://java.com/ipsum/primis/in/faucibus/orci/luctus.jsp?quis=diam&odio=cras&consequat=pellentesque&varius=volutpat&integer=dui&ac=maecenas&leo=tristique&pellentesque=est&ultrices=et&mattis=tempus&odio=semper&donec=est&vitae=quam&nisi=pharetra&nam=magna&ultrices=ac&libero=consequat&non=metus&mattis=sapien&pulvinar=ut&nulla=nunc&pede=vestibulum&ullamcorper=ante&augue=ipsum&a=primis&suscipit=in&nulla=faucibus&elit=orci&ac=luctus&nulla=et&sed=ultrices&vel=posuere&enim=cubilia&sit=curae&amet=mauris&nunc=viverra&viverra=diam&dapibus=vitae&nulla=quam&suscipit=suspendisse&ligula=potenti&in=nullam&lacus=porttitor&curabitur=lacus&at=at&ipsum=turpis&ac=donec&tellus=posuere&semper=metus&interdum=vitae&mauris=ipsum&ullamcorper=aliquam&purus=non&sit=mauris&amet=morbi&nulla=non&quisque=lectus&arcu=aliquam&libero=sit&rutrum=amet&ac=diam&lobortis=in', description: 'Fusce posuere felis sed lacus. Morbi sem mauris, laoreet ut, rhoncus aliquet, pulvinar sed, nisl. Nunc rhoncus dui vel sem.\n\nSed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', price: 613.88},
	{id: 43, name: 'Apples - Spartan', image: 'https://w3.org/pede/justo/lacinia/eget/tincidunt.json?id=ac&justo=neque&sit=duis&amet=bibendum&sapien=morbi&dignissim=non&vestibulum=quam&vestibulum=nec&ante=dui&ipsum=luctus&primis=rutrum&in=nulla&faucibus=tellus&orci=in&luctus=sagittis&et=dui&ultrices=vel&posuere=nisl&cubilia=duis&curae=ac&nulla=nibh&dapibus=fusce&dolor=lacus&vel=purus&est=aliquet&donec=at&odio=feugiat&justo=non&sollicitudin=pretium&ut=quis&suscipit=lectus&a=suspendisse&feugiat=potenti&et=in&eros=eleifend&vestibulum=quam&ac=a&est=odio&lacinia=in&nisi=hac&venenatis=habitasse&tristique=platea&fusce=dictumst&congue=maecenas&diam=ut&id=massa&ornare=quis&imperdiet=augue&sapien=luctus&urna=tincidunt&pretium=nulla&nisl=mollis&ut=molestie&volutpat=lorem&sapien=quisque&arcu=ut', description: 'Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.\n\nCurabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.\n\nPhasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', price: 758.13},
	{id: 44, name: 'Cabbage - Nappa', image: 'https://si.edu/magna.jpg?mauris=laoreet&sit=ut&amet=rhoncus&eros=aliquet&suspendisse=pulvinar&accumsan=sed&tortor=nisl&quis=nunc&turpis=rhoncus&sed=dui&ante=vel&vivamus=sem&tortor=sed&duis=sagittis&mattis=nam&egestas=congue&metus=risus&aenean=semper&fermentum=porta&donec=volutpat&ut=quam&mauris=pede&eget=lobortis&massa=ligula&tempor=sit&convallis=amet&nulla=eleifend&neque=pede&libero=libero&convallis=quis&eget=orci&eleifend=nullam&luctus=molestie&ultricies=nibh&eu=in&nibh=lectus&quisque=pellentesque&id=at&justo=nulla&sit=suspendisse&amet=potenti&sapien=cras&dignissim=in&vestibulum=purus&vestibulum=eu&ante=magna&ipsum=vulputate&primis=luctus&in=cum&faucibus=sociis&orci=natoque&luctus=penatibus&et=et', description: 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', price: 511.46},
	{id: 45, name: 'Beer - Sleemans Honey Brown', image: 'http://ted.com/quam/pede.js?suspendisse=morbi&potenti=odio&cras=odio&in=elementum&purus=eu&eu=interdum&magna=eu&vulputate=tincidunt&luctus=in&cum=leo&sociis=maecenas&natoque=pulvinar&penatibus=lobortis&et=est&magnis=phasellus&dis=sit&parturient=amet&montes=erat&nascetur=nulla&ridiculus=tempus&mus=vivamus&vivamus=in&vestibulum=felis&sagittis=eu&sapien=sapien&cum=cursus&sociis=vestibulum&natoque=proin&penatibus=eu&et=mi&magnis=nulla&dis=ac&parturient=enim&montes=in&nascetur=tempor&ridiculus=turpis&mus=nec&etiam=euismod&vel=scelerisque&augue=quam&vestibulum=turpis&rutrum=adipiscing&rutrum=lorem&neque=vitae&aenean=mattis&auctor=nibh&gravida=ligula&sem=nec&praesent=sem&id=duis&massa=aliquam&id=convallis&nisl=nunc&venenatis=proin&lacinia=at&aenean=turpis&sit=a&amet=pede&justo=posuere&morbi=nonummy&ut=integer&odio=non', description: 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.\n\nIn congue. Etiam justo. Etiam pretium iaculis justo.\n\nIn hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', price: 526.62},
	{id: 46, name: 'White Fish - Filets', image: 'https://vk.com/id/consequat/in/consequat.js?dignissim=cras&vestibulum=pellentesque&vestibulum=volutpat&ante=dui&ipsum=maecenas&primis=tristique&in=est&faucibus=et&orci=tempus&luctus=semper&et=est&ultrices=quam&posuere=pharetra&cubilia=magna&curae=ac&nulla=consequat&dapibus=metus&dolor=sapien&vel=ut&est=nunc&donec=vestibulum&odio=ante&justo=ipsum&sollicitudin=primis&ut=in&suscipit=faucibus&a=orci&feugiat=luctus&et=et&eros=ultrices&vestibulum=posuere&ac=cubilia&est=curae&lacinia=mauris&nisi=viverra&venenatis=diam&tristique=vitae&fusce=quam&congue=suspendisse&diam=potenti&id=nullam&ornare=porttitor&imperdiet=lacus&sapien=at&urna=turpis&pretium=donec&nisl=posuere&ut=metus&volutpat=vitae&sapien=ipsum&arcu=aliquam&sed=non&augue=mauris&aliquam=morbi&erat=non&volutpat=lectus&in=aliquam&congue=sit&etiam=amet&justo=diam&etiam=in&pretium=magna&iaculis=bibendum&justo=imperdiet&in=nullam&hac=orci&habitasse=pede&platea=venenatis&dictumst=non&etiam=sodales&faucibus=sed&cursus=tincidunt&urna=eu&ut=felis&tellus=fusce&nulla=posuere&ut=felis&erat=sed&id=lacus&mauris=morbi&vulputate=sem&elementum=mauris&nullam=laoreet&varius=ut&nulla=rhoncus&facilisi=aliquet&cras=pulvinar&non=sed&velit=nisl', description: 'Sed ante. Vivamus tortor. Duis mattis egestas metus.\n\nAenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', price: 4.59},
	{id: 47, name: 'Wasabi Powder', image: 'https://fema.gov/curabitur.js?leo=pede&odio=ac&condimentum=diam&id=cras&luctus=pellentesque&nec=volutpat&molestie=dui&sed=maecenas&justo=tristique&pellentesque=est&viverra=et&pede=tempus&ac=semper&diam=est&cras=quam&pellentesque=pharetra&volutpat=magna&dui=ac&maecenas=consequat&tristique=metus&est=sapien&et=ut&tempus=nunc&semper=vestibulum&est=ante&quam=ipsum&pharetra=primis&magna=in&ac=faucibus&consequat=orci&metus=luctus&sapien=et&ut=ultrices&nunc=posuere&vestibulum=cubilia&ante=curae&ipsum=mauris&primis=viverra&in=diam&faucibus=vitae&orci=quam&luctus=suspendisse&et=potenti&ultrices=nullam&posuere=porttitor&cubilia=lacus&curae=at&mauris=turpis&viverra=donec&diam=posuere&vitae=metus&quam=vitae&suspendisse=ipsum&potenti=aliquam&nullam=non&porttitor=mauris&lacus=morbi&at=non&turpis=lectus&donec=aliquam&posuere=sit&metus=amet&vitae=diam&ipsum=in&aliquam=magna&non=bibendum&mauris=imperdiet&morbi=nullam&non=orci&lectus=pede&aliquam=venenatis&sit=non&amet=sodales&diam=sed&in=tincidunt&magna=eu&bibendum=felis&imperdiet=fusce&nullam=posuere&orci=felis&pede=sed&venenatis=lacus&non=morbi&sodales=sem&sed=mauris&tincidunt=laoreet&eu=ut&felis=rhoncus&fusce=aliquet&posuere=pulvinar&felis=sed&sed=nisl&lacus=nunc&morbi=rhoncus&sem=dui&mauris=vel&laoreet=sem', description: 'Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', price: 102.84},
	{id: 48, name: 'Truffle Cups - Brown', image: 'https://nih.gov/nullam.aspx?in=mi&quam=pede&fringilla=malesuada&rhoncus=in&mauris=imperdiet&enim=et&leo=commodo&rhoncus=vulputate&sed=justo&vestibulum=in&sit=blandit&amet=ultrices&cursus=enim&id=lorem&turpis=ipsum&integer=dolor&aliquet=sit&massa=amet&id=consectetuer&lobortis=adipiscing&convallis=elit&tortor=proin&risus=interdum', description: 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.\n\nPraesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.\n\nCras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.', price: 256.47},
	{id: 49, name: 'Bread - Multigrain Oval', image: 'http://usa.gov/luctus/nec/molestie/sed/justo.jpg?in=habitasse&eleifend=platea&quam=dictumst&a=morbi&odio=vestibulum&in=velit&hac=id&habitasse=pretium&platea=iaculis&dictumst=diam&maecenas=erat&ut=fermentum&massa=justo&quis=nec&augue=condimentum&luctus=neque&tincidunt=sapien&nulla=placerat&mollis=ante&molestie=nulla&lorem=justo&quisque=aliquam&ut=quis&erat=turpis&curabitur=eget&gravida=elit&nisi=sodales&at=scelerisque&nibh=mauris&in=sit&hac=amet&habitasse=eros&platea=suspendisse&dictumst=accumsan&aliquam=tortor&augue=quis&quam=turpis&sollicitudin=sed&vitae=ante&consectetuer=vivamus&eget=tortor&rutrum=duis&at=mattis&lorem=egestas&integer=metus&tincidunt=aenean&ante=fermentum&vel=donec&ipsum=ut&praesent=mauris&blandit=eget&lacinia=massa&erat=tempor&vestibulum=convallis&sed=nulla&magna=neque&at=libero&nunc=convallis&commodo=eget&placerat=eleifend&praesent=luctus&blandit=ultricies&nam=eu&nulla=nibh&integer=quisque&pede=id&justo=justo&lacinia=sit&eget=amet&tincidunt=sapien&eget=dignissim&tempus=vestibulum&vel=vestibulum&pede=ante&morbi=ipsum&porttitor=primis', description: 'Duis bibendum. Morbi non quam nec dui luctus rutrum. Nulla tellus.\n\nIn sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.\n\nSuspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', price: 318.4},
	{id: 50, name: 'Beef Wellington', image: 'https://webnode.com/eros/viverra.js?morbi=auctor&ut=gravida&odio=sem', description: 'Fusce consequat. Nulla nisl. Nunc nisl.', price: 556.28}];

const itemsPerPage = 10; // Cantidad de productos por página
const ProductList = (): JSX.Element => {
	const [products, setProducts] = useState(mockProducts);
	const [pageNumber, setPageNumber] = useState(0);

	const itemsPerPage = 7; // Cambia el número de productos por página según tus necesidades
	const pageCount = Math.ceil(products.length / itemsPerPage);
	const displayedProducts = products.slice(
		pageNumber * itemsPerPage,
		(pageNumber + 1) * itemsPerPage,
	);

	const handlePageClick = ({selected}) => {
		setPageNumber(selected);
	};

	return (
		<>
			<Header />
			<div className='flex flex-col justify-between pt-16 min-h-screen max-h-max'>
				<div className='bg-gray-100 dark:bg-gray-900 py-8 flex flex-col'>
					<div className='container mx-auto px-4 flex-grow'>
						<div className='flex'>
							<div className='w-1/4 p-4'>
								{/* Barra lateral de filtros */}
								<div className='mb-6'>
									<label className='text-gray-600 dark:text-gray-400'>Categoría</label>
									<select className='block w-full mt-1 border rounded-lg shadow-sm focus:border-blue-500 dark:focus:border-blue-400'>
										<option value='nuevo'>Nuevo</option>
										<option value='usado'>Usado</option>
									</select>
								</div>
								<div className='mb-6'>
									<label className='text-gray-600 dark:text-gray-400'>Precio</label>
									<select className='block w-full mt-1 border rounded-lg shadow-sm focus:border-blue-500 dark:focus:border-blue-400'>
										<option value='0-100'>$0 - $100</option>
										<option value='100-200'>$100 - $200</option>
										<option value='200-500'>$200 - $500</option>
										<option value='500+'>$500+</option>
									</select>
								</div>
								<div>
									<label className='text-gray-600 dark:text-gray-400'>Ordenar por</label>
									<select className='block w-full mt-1 border rounded-lg shadow-sm focus-border-blue-500 dark:focus-border-blue-400'>
										<option value='relevancia'>Relevancia</option>
										<option value='precio-asc'>Precio Ascendente</option>
										<option value='precio-desc'>Precio Descendente</option>
									</select>
								</div>
							</div>
							<div className='w-3/4 flex-grow'>
								<h1 className='text-3xl font-semibold text-gray-800 dark:text-gray-200 mb-6'>
                Lista de Productos
								</h1>
								<div className='grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6'>
									{displayedProducts.map(product => (
										<div
											key={product.id}
											className='bg-white dark:bg-gray-800 shadow-lg rounded-lg overflow-hidden'
										>
											<img
												src={product.image}
												alt={product.name}
												className='w-full h-48 object-cover object-center'
											/>
											<div className='p-4'>
												<h2 className='text-2xl text-gray-800 dark:text-gray-200 font-semibold'>
													{product.name}
												</h2>
												<p className='text-gray-600 dark:text-gray-400'>{product.description}</p>
												<p className='mt-2 text-black font-bold'>${product.price}</p>
											</div>
										</div>
									))}
								</div>
								<ReactPaginate
									previousLabel={
										<i className='fas fa-chevron-left mr-2 text-gray-600 dark:text-gray-400'></i>
									}
									nextLabel={
										<i className='fas fa-chevron-right ml-2 text-gray-600 dark:text-gray-400'></i>
									}
									breakLabel={'...'}
									breakClassName={'break-me'}
									pageCount={pageCount}
									marginPagesDisplayed={2}
									pageRangeDisplayed={5}
									onPageChange={handlePageClick}
									containerClassName={'mt-6 flex justify-center'}
									subContainerClassName={'pages pagination'}
									activeClassName={
										'text-blue-500 border-blue-500 dark:text-blue-400 dark:border-blue-400'
									}
									previousClassName={'border rounded-l-full text-gray-600 dark:text-gray-400'}
									nextClassName={'border rounded-r-full text-gray-600 dark:text-gray-400'}
									pageLinkClassName={
										'px-3 py-2 border rounded-full border-gray-300 dark:border-gray-600 text-gray-600 dark:text-gray-400 hover:bg-gray-100 dark:hover-bg-gray-800'
									}
								/>
							</div>
						</div>
					</div>
				</div>
				<Footer />
			</div>
		</>
	);
};

export default ProductList;

